import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import SwitchTheme from '../components/SwitchTheme'
// import styles from '../styles/Home.module.css'

export const config = {
  unstable_runtimeJS: false
}

export default function Home () {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>
          Welcome to <a href="https://nextjs.org">Demo App!</a>
        </h1>

        <SwitchTheme />

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>

        <div className="grid">
          <Card
            url="https://nextjs.org/docs"
            title="Documentation &rarr;"
            description="Find in-depth information about Next.js features and API."
          />

          <Card
            url="https://github.com/vercel/next.js/tree/canary/examples"
            title="Card component"
            description="This is a card component created with React and NextJS."
          />
        </div>
      </main>

      <footer className="container">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
